
const Sequelize = require('sequelize')
const configuration = require('../config/database.js')
const Adress = require('../models/Adresses/Adress.model.js')
const Categorie = require('../models/categorie_packages/Categorie.models.js')
const Ivoice = require('../models/ivoice/Ivoice.models.js')
const method = require('../models/method_shipping/method_shipping.js')
const Packages = require('../models/packages/Package.model.js')
const PackageDetalhes = require('../models/package_detalhes/PackageDetalhes.model.js')
const Shippings = require('../models/Shippings/Shippings.js')
const Token = require('../models/Token/Token.js')
const Users = require('../models/Users/Users.js')
const Conection = new Sequelize(configuration)

Users.init(Conection)
Adress.init(Conection)
Adress.association(Conection.models)
Packages.init(Conection)
method.init(Conection)
Categorie.init(Conection)
PackageDetalhes.init(Conection)
Token.init(Conection)
Ivoice.init(Conection)
Packages.association(Conection.models)
PackageDetalhes.association(Conection.models)
Ivoice.association(Conection.models)
Token.association(Conection.models)
Shippings.init(Conection)
Shippings.association(Conection.models)

module.exports = Conection